name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Copy Template
        run: |
          uvx copier copy \
            ./ \
            /tmp/test-copier \
            -d project_name=test-copier \
            -d python_version=${{ matrix.python-version }} \
            -d package_name=test_copier \
            -d description="Test Copier" \
            -d author_name=test-copier \
            -d author_email=test-copier@example.com

      - name: Test Package Installation
        working-directory: /tmp/test-copier
        run: |
          uv sync

      - name: Test Ruff Format
        working-directory: /tmp/test-copier
        run: |
          uv run ruff format --check --diff .

      - name: Test Ruff Lint
        working-directory: /tmp/test-copier
        run: |
          uv run ruff check --output-format=github .

      - name: Test pytest
        working-directory: /tmp/test-copier
        run: |
          uv run pytest -vs

      - name: Test Docker
        working-directory: /tmp/test-copier
        run: |
          ./docker/build.sh
          ./docker/run.sh

      - name: Test Docker Compose
        working-directory: /tmp/test-copier
        run: |
          docker compose build
          docker compose up -d
          docker compose down

  results:
    name: CI Status Check
    runs-on: ubuntu-latest
    needs: [ci]
    if: always()
    steps:
      - name: Evaluate CI status
        run: |
          if contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'); then
            echo "Some CI checks failed"
            exit 1
          else
            echo "All CI checks passed"
            exit 0
          fi
